markdown: rdiscount
highlighter: pygments
permalink: post/:year/:month/:day/:title.html
paginate: 6
paginate_path: page/:num

blog:
    name:                                                Yang
    description:                                         性疏狂，不思量，和风细雨，不动明王
    
author:
    name:                                                Yang
    email:                                               609560302@qq.com