markdown: rdiscount
highlighter: pygments
permalink: post/:year/:month/:day/:title.html
paginate: 6
paginate_path: page/:num

blog:
    name:                                                Yang
    description:                                         性疏狂，不思量，和风细雨，不动明王
    title:                                               Yang Blog
    url:                                                 http://yzr007.github.io/
    duoshuo:                                             Aad-yang
    tongji:                                              Aad-yang
    qiniu:                                               # 七牛云地址
author:
    name:                                                Yang
    email:                                               609560302@qq.com	
    weibo:                                               http://weibo.com/AAD_YANG
    google-plus:                                         https://plus.google.com/
    github:                                              https://github.com/yzr007
    logo:                                                /res/img/avatar.jpg
    douban:
        name:                                            二十年梨花
        key:                                             0a7dfe96843928fb1f79fbc38cab7af1